annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 9.9.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: SonarQube(TM) is an open source quality management platform that analyzes and measures code's technical quality. It enables developers to detect code issues, vulnerabilities, and bugs in early stages.
home: https://github.com/bitnami/charts/tree/main/bitnami/sonarqube
icon: https://bitnami.com/assets/stacks/sonarqube/img/sonarqube-stack-220x234.png
keywords:
  - sonarqube
  - code-quality
  - code-review
  - static-analysis
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: sonarqube
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/sonarqube
  - https://github.com/SonarSource/sonarqube
version: 2.1.0
