{{- if .Values.metrics.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-jmx-conf" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  sonarqube-prometheus.yml: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.jmx.configuration "context" $ ) | nindent 4 }}
{{- end -}}
