controller:
  enableStatefulSet: true

#server:
#  autoscaling:
#    enabled: true
#    minReplicas: 2

#repoServer:
#  autoscaling:
#    enabled: true
#    minReplicas: 2

configs:
  secret:
    argocdServerAdminPassword: $2a$10$lgcvwdvggWeLl1AN14NWsePcWQczWHRQH2eiUNL9w/gN6NaelDl.G

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, ArgoCDAdmins, role:admin

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://app-argo.virtapp.io
  oidc.config: |
    name: Keycloak
    issuer: https://app.virtapp.io/auth/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]

